name: Run Tests
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn jest --testPathPattern=test --detectOpenHandles --color --forceExit --coverage
      - run: yarn
      - run: yarn build
      - run: yarn test
